import Head from "next/head";
import Link from "next/link";
import Footer from "../../components/footer/Footer";
import styles from "../../styles/Events.module.css";
import EventCard from "../../components/eventCard/EventCard";
import { Button } from "@mui/material";

import { db } from "../../config/firebaseConfig";
import { collection, query, where, getDocs } from "firebase/firestore";
import { useEffect, useState } from "react";

export default function Events() {
  const eventsCollectionRef = collection(db, "events");
  const [events, setevents] = useState([]);

  useEffect(() => {
    const getEvents = async () => {
      const data = await getDocs(eventsCollectionRef);
      setevents(data.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    };

    getEvents();
  }, []);
  console.log(events);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button>
          <Link href="/events/add-event">Add Event</Link>
        </Button>
        <h3 className={styles.title}>
          Popular <a href="">Events</a>
        </h3>
        <div className={styles.events__container}>
          {events.map((event) => {
            return (
              <EventCard
                key={event.id}
                title={event.title}
                venue={event.venue}
                date={event.date}
              />
            );
          })}
        </div>
      </main>

      <Footer />
    </div>
  );
}
