import Head from "next/head";
import Link from "next/link";
import Footer from "../../components/footer/Footer";
import styles from "../../styles/Events.module.css";
import EventCard from "../../components/eventCard/EventCard";
import { Button } from "@mui/material";

export default function Events() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button>
          <Link href="/events/add-event">Add Event</Link>
        </Button>
        <h3 className={styles.title}>
          Popular <a href="">Events</a>
        </h3>
        <div className={styles.events__container}>
          <EventCard />
          <EventCard />
          <EventCard />
          <EventCard />
          <EventCard />
          <EventCard />
        </div>
      </main>

      <Footer />
    </div>
  );
}
