import { Avatar, Button, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { Carousel } from "react-responsive-carousel";

import Footer from "../../../components/footer/Footer";
import styles from "./event.module.css";

const product = { 
  images: [
    "https://images.unsplash.com/photo-1567446362432-f30e36eb96c8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80", "https://images.unsplash.com/photo-1567446362432-f30e36eb96c8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80", "https://images.unsplash.com/photo-1567446362432-f30e36eb96c8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
  ]
}
  


export default function Events() {
  const router = useRouter();
  const { id } = router.query;
  return (
    <div className={styles.container}>
      <Head>
        <title>event {id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.main__hero}>
          <Image
            className={styles.main__hero__image}
            alt="image"
            src="https://images.unsplash.com/photo-1567446362432-f30e36eb96c8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
            layout="fill"
            objectFit="cover"
            priority
          />
          <h1 className={styles.main__title}>
            Event Title goes here Lorem ipsum dolor sit amet, consectetur
            adipiscing elit, sed do eiusmod tempor
          </h1>
        </section>
        <section className={styles.main__content}>
          <div className={styles.main__content__image}>
            <Image
              alt="event image"
              src="https://source.unsplash.com/GiQ9Yck2h3E/400x400"
              layout="fill"
              objectFit="contain"
            />
          </div>
          <div className={styles.main__content__details}>
            <div className={styles.main__content__details__header}>
              <Typography variant="subtitle1">Seminar</Typography>
              <Typography variant="h6">
                UCA Academic Symposium - Student
              </Typography>
            </div>
            <div className={styles.main__content__details__box}>
              <div>
                <Typography variant="subtitle2">Date</Typography>
                <Typography variant="body1">September 2nd 2022</Typography>
              </div>
              <div>
                <Typography variant="subtitle2">Time</Typography>
                <Typography variant="body1">8:00 A.M</Typography>
              </div>
              <div>
                <Typography variant="subtitle2">Venue</Typography>
                <Typography variant="body1">UCA Hall, New York</Typography>
              </div>
            </div>
            <Typography variant="body1">
              Certain be ye amiable by exposed so celebrated estimating
              excellence do furnished do otherwise conveying attempted. These
              are just some of the numerous reasons of choosing and sticking
              with us alone.
            </Typography>
            <Button
              variant="contained"
              className={styles.main__content__details__button}
            >
              Book Your Seat
            </Button>
          </div>
        </section>
        <section className={styles.main__details}>
          <Typography variant="body1">
            Certain be ye amiable by exposed so celebrated estimating excellence
            do furnished do otherwise conveying attempted. These are just some
            of the numerous reasons of choosing and sticking with us alone.
            Certain be ye amiable by exposed so celebrated estimating excellence
            do furnished do otherwise conveying attempted. These are just some
            of the numerous reasons of choosing and sticking with us alone.
          </Typography>
          {/* <Carousel
            axis="horizontal"
            infiniteLoop={true}
            autoPlay={true}
            swipeable={true}
            renderThumbs={() =>
              product.images.map((img, idx) => (
                <div key={idx} className={styles.images}>
                  <Image
                    src={img}
                    layout="fill"
                    objectFit="contain"
                    alt="logo"
                  ></Image>
                </div>
              ))
            }
          >
            {product.images.length !== 0 &&
              product.images.map((img, idx) => (
                <Image
                  key={idx}
                  src={img}
                  alt={`${product.title} preview ${idx}`}
                  layout="responsive"
                  width={650}
                  height={650}
                  priority={idx === 0}
                ></Image>
              ))}
          </Carousel> */}
        </section>
      </main>
      <Footer />
    </div>
  );
}
